hobby = input("Hva er din hobby?")
print("Din hobby er", hobby)
bosted = input("Hva kalles ditt bosted? ")
print("Ditt bosted er", bosted)
farge = input("Hva er din favorittfarge? ")
print("Din favorittfarge er", farge)
